name: lobby
version: '1.0'
main: lobby.lobby.Lobby
api-version: '1.21'

commands:
  admin:
    description: Toggle admin title for a player
    usage: /admin <player>
  staff:
    description: Toggle staff title for a player
    usage: /staff <player>
  bwegg:
    description: Get Bedwars NPC spawn egg
    usage: /bwegg
  debwegg:
    description: Delete nearest Bedwars NPC
    usage: /debwegg
